name: aqlinter
description: "This is AQoong's favorit linter set"
version: 3.0.0
homepage: "https://aqoong.site"
repository: "https://github.com/aqoong/flutter-aqlinter"
topics:
  - lints

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

license: MIT